### ISSUE TITLE
Revising Send and Sync bounds was a breaking change

### ISSUE THREAD

**Issue by bluurryy** [orxfun/orx-concurrent-ordered-bag#21]
`orx-parallel` won't compile anymore `orx-concurrent-ordered-bag` version 2.14.0.

It compiles fine with version 2.13.0.

I get errors like this:

```
error[E0277]: `O` cannot be sent between threads safely
   --> /home/z/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/orx-parallel-2.4.0/src/runner/thread_runner_compute/collect_ordered.rs:31:54
    |
31  |                 Some((idx, value)) => unsafe { o_bag.set_value(offset + idx, map1(value)) },
    |                                                      ^^^^^^^^^ `O` cannot be sent between threads safely
    |
note: required by a bound in `ConcurrentOrderedBag::<T, P>::set_value`
   --> /home/z/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/orx-concurrent-ordered-bag-2.14.0/src/bag.rs:331:12
    |
329 |     pub unsafe fn set_value(&self, idx: usize, value: T)
    |                   --------- required by a bound in this associated function
330 |     where
331 |         T: Send,
    |            ^^^^ required by this bound in `ConcurrentOrderedBag::<T, P>::set_value`
help: consider further restricting type parameter `O` with trait `Send`
    |
19  |     P: IntoConcurrentPinnedVec<O>, O: std::marker::Send
    |                                    ++++++++++++++++++++
```

**Comment by orxfun** [comment]
@bluurryy , thanks for pointing to this and very sorry for the problem. The new "orx-parallel" version (2.5.0) is now released and should work properly, could you please try?

orx-parallel = "2.5.0"
https://github.com/orxfun/orx-parallel/releases/tag/2.5.0

**Comment by orxfun** [comment]
Yes, you're totally right, I'm on it.
Thanks.
